In [51]:
import numpy as np
import cv2
import os
from PIL import Image
import pickle
import face_recognition as fr

In [52]:
face_cascade = cv2.CascadeClassifier('haarcascade_frontalface_alt2.xml')
cap = cv2.VideoCapture(0)

In [53]:
while(True):
    #to capture frame by frame
    ret, frame = cap.read()
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    faces = face_cascade.detectMultiScale(
        gray,
        scaleFactor=1.5,
        minNeighbors=5
        )
    for (x, y, w, h) in faces:
        print(x, y, w, h)
        roi_gray = gray[y:y+h, x:x+w]
        roi_color = frame[y:y+h, x:x+w]
        #id_, conf = 
        #recognizer deep learning model
        
        img_item = "img.png"
        cv2.imwrite(img_item, roi_gray)
        
        color = (255, 255, 255)
        thinkness = 2
        width = x + w
        height = y + h
        cv2.rectangle(frame, (x, y), (width, height), color, thinkness)
        
    #to display the results of the frame
    cv2.imshow('frame', frame)
    if cv2.waitKey(20) & 0xFF == ord('q'):
        break

cap.release()
cv2.destroyAllWindows()

308 410 101 101
409 359 101 101
427 361 101 101
428 375 101 101
427 360 101 101
423 362 101 101
418 364 101 101
422 361 101 101
432 360 101 101
484 391 101 101
494 394 101 101
492 400 101 101
485 400 101 101
482 400 101 101
483 400 101 101
483 399 101 101
483 396 101 101
482 405 101 101
483 401 101 101
485 405 101 101
487 406 101 101
484 404 101 101
482 399 101 101
484 400 101 101
484 404 101 101
485 407 101 101
488 409 101 101
487 410 101 101
488 407 101 101
485 406 101 101
485 403 101 101
486 401 101 101
484 400 101 101
485 402 101 101
485 400 101 101
478 394 101 101
480 396 101 101
483 398 101 101
479 394 101 101
478 396 101 101
478 394 101 101
483 392 101 101
482 399 101 101
482 414 101 101
461 418 101 101
453 418 101 101
932 290 342 342
445 416 101 101
451 419 101 101
932 290 342 342
458 421 101 101
932 290 342 342
933 278 342 342
455 419 101 101
455 430 101 101
457 430 101 101
932 273 342 342
509 395 101 101
515 391 101 101
932 273 342 342
508 395 101 101
932 273 342 342
509 395 

In [54]:
image_dir = os.path.join('images')
print(image_dir)

images


In [55]:
for root, dirs, files in os.walk(image_dir):
    for file in files:
        if file.endswith('png') or file.endswith('jpg'):
            path = os.path.join(root, file)
            label = os.path.basename(os.path.dirname(path)).replace(" ", '-').lower()
            print(label, path)

bill images/bill/8.jpg
bill images/bill/9.jpg
bill images/bill/12.jpg
bill images/bill/11.jpg
bill images/bill/10.jpg
bill images/bill/5.png
bill images/bill/7.jpg
bill images/bill/6.jpg
bill images/bill/2.jpg
bill images/bill/3.jpg
bill images/bill/1.jpg
ibrahim images/ibrahim/8.jpg
ibrahim images/ibrahim/9.jpg
ibrahim images/ibrahim/test1.jpg
ibrahim images/ibrahim/test2.jpg
ibrahim images/ibrahim/test.jpg
ibrahim images/ibrahim/4.jpg
ibrahim images/ibrahim/5.jpg
ibrahim images/ibrahim/7.jpg
ibrahim images/ibrahim/6.jpg
ibrahim images/ibrahim/2.jpg
ibrahim images/ibrahim/3.jpg
ibrahim images/ibrahim/1.jpg
jassim images/jassim/8.jpg
jassim images/jassim/9.jpg
jassim images/jassim/14.jpg
jassim images/jassim/15.jpg
jassim images/jassim/16.jpg
jassim images/jassim/12.jpg
jassim images/jassim/13.jpg
jassim images/jassim/11.jpg
jassim images/jassim/10.jpg
jassim images/jassim/4.jpg
jassim images/jassim/5.jpg
jassim images/jassim/7.jpg
jassim images/jassim/6.jpg
jassim images/jassim/2.jpg


In [56]:
pil_image = Image.open(path).convert("L") #grayscale
image_array = np.array(pil_image, 'uint8')
print(image_array)

[[176 174 169 ... 174 174 174]
 [176 174 169 ... 174 174 174]
 [176 175 170 ... 174 174 174]
 ...
 [ 53  53  53 ...  14  13  12]
 [ 53  53  53 ...  13  13  12]
 [ 53  53  53 ...  13  12  12]]


In [57]:
current_id = 0
label_ids = {}
y_labels = []
x_train = []

if not label in label_ids:
    label_ids[label] = current_id
    current_id += 1
    id_ = label_ids[label]
#id_ = label_ids[label]
print(label_ids)
#y_labels.append(label)
#x_train.append(path)
            

{'obama': 0}


In [58]:
#face_cascade = cv2.CascadeClassifier('haarcascade_frontalface_alt2.xml')
face_recognizer = cv2.face.LBPHFaceRecognizer_create()


current_id = 0
label_ids = {}
y_labels = []
x_train = []

for root, dirs, files in os.walk(image_dir):
    for file in files:
        if file.endswith('png') or file.endswith('jpg'):
            path = os.path.join(root, file)
            label = os.path.basename(os.path.dirname(path)).replace(" ", '-').lower()
            #print(label, path)
            
            
            if not label in label_ids:
                label_ids[label] = current_id
                current_id += 1
            id_ = label_ids[label]
            #print(label_ids)
            #y_labels.append(label)
            #x_train.append(path)
            
            
            pil_image = Image.open(path).convert("L") #grayscale
            size = (550,550)
            final_image = pil_image.resize(size, Image.ANTIALIAS)
            image_array = np.array(pil_image, 'uint8')
            #print(image_array)
            
            faces = face_cascade.detectMultiScale(
                image_array,
                scaleFactor=1.5,
                minNeighbors=5
            )
            for (x,y,w,h) in faces:
                roi = image_array[y:y+h, x:x+w]
                x_train.append(roi)
                y_labels.append(id_)

#print(y_labels)
#print(x_train)

In [59]:
with open("labels.pickle", "wb") as f:
    pickle.dump(label_ids, f)
face_recognizer.train(x_train, np.array(y_labels))
face_recognizer.save("trainner.yml")

In [60]:
face_recognizer.read("trainner.yml")

In [61]:
labels1 = {}
#with open("labels.pickle", "rb") as f:
   # labels1 = pickle.load(label_ids, f)
with open("labels.pickle", "rb") as f:
    og_labels = pickle.load(f)
    labels1 = {v:k for k,v in og_labels.items()}


    
for (x, y, w, h) in faces:
    
    print(x, y, w, h)
    roi_gray = gray[y:y+h, x:x+w]
    roi_color = frame[y:y+h, x:x+w]
               
            
            #recognizer deep learning model this
    id_, conf = face_recognizer.predict(roi_gray)
    if conf>=40:
        #and conf<=80
        print(id_)
        print(labels1[id_])
        font = cv2.FONT_HERSHEY_SIMPLEX
        name = labels1[id_]
        color = (255,255,255)
        stroke = 2
        cv2.putText(frame, name, (x,y), font, 1, color, stroke, cv2.LINE_AA)
        
        img_item = "images/jassim/11.jpg"
        cv2.imwrite(img_item, roi_gray)
        
        color = (255, 255, 255)
        thinkness = 2
        width = x + w
        height = y + h
        #cv2.rectangle(frame, (x, y), (width, height), color, thinkness)
        
    #to display the results of the frame
    cv2.imshow('frame', frame)
    if cv2.waitKey(20) & 0xFF == ord('q'):
        break

cap.release()
cv2.destroyAllWindows()

453 192 513 513
3
obama
